version: '3.8'

networks:
  larazine:
    name: larazine

services:
  app:
    build: .
    container_name: larazine_app
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 9005:80
    volumes:
      - ./:/app
    networks:
      - larazine

  composer:
    image: composer:latest
    container_name: larazine_composer
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - larazine

  artisan:
    build: .
    container_name: larazine_artisan
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: [ "php", "artisan" ]
    networks:
      - larazine

  mysql:
    image: mysql:5.7.22
    container_name: larazine_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3333:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: larazine
      MYSQL_ROOT_PASSWORD: larazine
      SERVICE_NAME: mysql
    networks:
      - larazine