version: '3.8'

networks:
  larazine:
    name: larazine

services:
  nginx:
    image: nginx:stable-alpine
    container_name: larazine_nginx
    restart: unless-stopped
    depends_on:
      - php
      - mysql
    ports:
      - 9000:80
    volumes:
      - ./:/var/www/html
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    networks:
      - larazine

  php:
    build: .
    container_name: larazine_php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - larazine

  composer:
    image: composer:latest
    container_name: larazine_composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - larazine

  artisan:
    build: .
    container_name: larazine_artisan
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ "php", "artisan" ]
    networks:
      - larazine

  mysql:
    image: mysql:5.7.22
    container_name: larazine_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3333:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: larazine
      MYSQL_ROOT_PASSWORD: larazine
      SERVICE_NAME: mysql
    networks:
      - larazine